// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alerter.proto

package ds.alerter;

/**
 * Protobuf type {@code alerter.AlertDetails}
 */
public  final class AlertDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:alerter.AlertDetails)
    AlertDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AlertDetails.newBuilder() to construct.
  private AlertDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AlertDetails() {
    alertId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AlertDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ds.alerter.AlertMessage.Builder subBuilder = null;
            if (alertMessage_ != null) {
              subBuilder = alertMessage_.toBuilder();
            }
            alertMessage_ = input.readMessage(ds.alerter.AlertMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(alertMessage_);
              alertMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            alertId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.alerter.AlerterImpl.internal_static_alerter_AlertDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.alerter.AlerterImpl.internal_static_alerter_AlertDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.alerter.AlertDetails.class, ds.alerter.AlertDetails.Builder.class);
  }

  public static final int ALERTMESSAGE_FIELD_NUMBER = 1;
  private ds.alerter.AlertMessage alertMessage_;
  /**
   * <code>.alerter.AlertMessage alertMessage = 1;</code>
   */
  public boolean hasAlertMessage() {
    return alertMessage_ != null;
  }
  /**
   * <code>.alerter.AlertMessage alertMessage = 1;</code>
   */
  public ds.alerter.AlertMessage getAlertMessage() {
    return alertMessage_ == null ? ds.alerter.AlertMessage.getDefaultInstance() : alertMessage_;
  }
  /**
   * <code>.alerter.AlertMessage alertMessage = 1;</code>
   */
  public ds.alerter.AlertMessageOrBuilder getAlertMessageOrBuilder() {
    return getAlertMessage();
  }

  public static final int ALERTID_FIELD_NUMBER = 2;
  private int alertId_;
  /**
   * <code>int32 alertId = 2;</code>
   */
  public int getAlertId() {
    return alertId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (alertMessage_ != null) {
      output.writeMessage(1, getAlertMessage());
    }
    if (alertId_ != 0) {
      output.writeInt32(2, alertId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (alertMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAlertMessage());
    }
    if (alertId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, alertId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.alerter.AlertDetails)) {
      return super.equals(obj);
    }
    ds.alerter.AlertDetails other = (ds.alerter.AlertDetails) obj;

    boolean result = true;
    result = result && (hasAlertMessage() == other.hasAlertMessage());
    if (hasAlertMessage()) {
      result = result && getAlertMessage()
          .equals(other.getAlertMessage());
    }
    result = result && (getAlertId()
        == other.getAlertId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAlertMessage()) {
      hash = (37 * hash) + ALERTMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getAlertMessage().hashCode();
    }
    hash = (37 * hash) + ALERTID_FIELD_NUMBER;
    hash = (53 * hash) + getAlertId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.alerter.AlertDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alerter.AlertDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alerter.AlertDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alerter.AlertDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alerter.AlertDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alerter.AlertDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alerter.AlertDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.alerter.AlertDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.alerter.AlertDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.alerter.AlertDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.alerter.AlertDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.alerter.AlertDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.alerter.AlertDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code alerter.AlertDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:alerter.AlertDetails)
      ds.alerter.AlertDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.alerter.AlerterImpl.internal_static_alerter_AlertDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.alerter.AlerterImpl.internal_static_alerter_AlertDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.alerter.AlertDetails.class, ds.alerter.AlertDetails.Builder.class);
    }

    // Construct using ds.alerter.AlertDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (alertMessageBuilder_ == null) {
        alertMessage_ = null;
      } else {
        alertMessage_ = null;
        alertMessageBuilder_ = null;
      }
      alertId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.alerter.AlerterImpl.internal_static_alerter_AlertDetails_descriptor;
    }

    @java.lang.Override
    public ds.alerter.AlertDetails getDefaultInstanceForType() {
      return ds.alerter.AlertDetails.getDefaultInstance();
    }

    @java.lang.Override
    public ds.alerter.AlertDetails build() {
      ds.alerter.AlertDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.alerter.AlertDetails buildPartial() {
      ds.alerter.AlertDetails result = new ds.alerter.AlertDetails(this);
      if (alertMessageBuilder_ == null) {
        result.alertMessage_ = alertMessage_;
      } else {
        result.alertMessage_ = alertMessageBuilder_.build();
      }
      result.alertId_ = alertId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.alerter.AlertDetails) {
        return mergeFrom((ds.alerter.AlertDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.alerter.AlertDetails other) {
      if (other == ds.alerter.AlertDetails.getDefaultInstance()) return this;
      if (other.hasAlertMessage()) {
        mergeAlertMessage(other.getAlertMessage());
      }
      if (other.getAlertId() != 0) {
        setAlertId(other.getAlertId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.alerter.AlertDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.alerter.AlertDetails) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ds.alerter.AlertMessage alertMessage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ds.alerter.AlertMessage, ds.alerter.AlertMessage.Builder, ds.alerter.AlertMessageOrBuilder> alertMessageBuilder_;
    /**
     * <code>.alerter.AlertMessage alertMessage = 1;</code>
     */
    public boolean hasAlertMessage() {
      return alertMessageBuilder_ != null || alertMessage_ != null;
    }
    /**
     * <code>.alerter.AlertMessage alertMessage = 1;</code>
     */
    public ds.alerter.AlertMessage getAlertMessage() {
      if (alertMessageBuilder_ == null) {
        return alertMessage_ == null ? ds.alerter.AlertMessage.getDefaultInstance() : alertMessage_;
      } else {
        return alertMessageBuilder_.getMessage();
      }
    }
    /**
     * <code>.alerter.AlertMessage alertMessage = 1;</code>
     */
    public Builder setAlertMessage(ds.alerter.AlertMessage value) {
      if (alertMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        alertMessage_ = value;
        onChanged();
      } else {
        alertMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.alerter.AlertMessage alertMessage = 1;</code>
     */
    public Builder setAlertMessage(
        ds.alerter.AlertMessage.Builder builderForValue) {
      if (alertMessageBuilder_ == null) {
        alertMessage_ = builderForValue.build();
        onChanged();
      } else {
        alertMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.alerter.AlertMessage alertMessage = 1;</code>
     */
    public Builder mergeAlertMessage(ds.alerter.AlertMessage value) {
      if (alertMessageBuilder_ == null) {
        if (alertMessage_ != null) {
          alertMessage_ =
            ds.alerter.AlertMessage.newBuilder(alertMessage_).mergeFrom(value).buildPartial();
        } else {
          alertMessage_ = value;
        }
        onChanged();
      } else {
        alertMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.alerter.AlertMessage alertMessage = 1;</code>
     */
    public Builder clearAlertMessage() {
      if (alertMessageBuilder_ == null) {
        alertMessage_ = null;
        onChanged();
      } else {
        alertMessage_ = null;
        alertMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.alerter.AlertMessage alertMessage = 1;</code>
     */
    public ds.alerter.AlertMessage.Builder getAlertMessageBuilder() {
      
      onChanged();
      return getAlertMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.alerter.AlertMessage alertMessage = 1;</code>
     */
    public ds.alerter.AlertMessageOrBuilder getAlertMessageOrBuilder() {
      if (alertMessageBuilder_ != null) {
        return alertMessageBuilder_.getMessageOrBuilder();
      } else {
        return alertMessage_ == null ?
            ds.alerter.AlertMessage.getDefaultInstance() : alertMessage_;
      }
    }
    /**
     * <code>.alerter.AlertMessage alertMessage = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ds.alerter.AlertMessage, ds.alerter.AlertMessage.Builder, ds.alerter.AlertMessageOrBuilder> 
        getAlertMessageFieldBuilder() {
      if (alertMessageBuilder_ == null) {
        alertMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ds.alerter.AlertMessage, ds.alerter.AlertMessage.Builder, ds.alerter.AlertMessageOrBuilder>(
                getAlertMessage(),
                getParentForChildren(),
                isClean());
        alertMessage_ = null;
      }
      return alertMessageBuilder_;
    }

    private int alertId_ ;
    /**
     * <code>int32 alertId = 2;</code>
     */
    public int getAlertId() {
      return alertId_;
    }
    /**
     * <code>int32 alertId = 2;</code>
     */
    public Builder setAlertId(int value) {
      
      alertId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 alertId = 2;</code>
     */
    public Builder clearAlertId() {
      
      alertId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:alerter.AlertDetails)
  }

  // @@protoc_insertion_point(class_scope:alerter.AlertDetails)
  private static final ds.alerter.AlertDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.alerter.AlertDetails();
  }

  public static ds.alerter.AlertDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AlertDetails>
      PARSER = new com.google.protobuf.AbstractParser<AlertDetails>() {
    @java.lang.Override
    public AlertDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AlertDetails(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AlertDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AlertDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.alerter.AlertDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

