// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alerter.proto

package ds.alerter;

public interface AlertMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alerter.AlertMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.alerter.AlertMessage.PriorityLevel priorityLevel = 1;</code>
   */
  int getPriorityLevelValue();
  /**
   * <code>.alerter.AlertMessage.PriorityLevel priorityLevel = 1;</code>
   */
  ds.alerter.AlertMessage.PriorityLevel getPriorityLevel();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
