// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alerter.proto

package ds.alerter;

public interface alertIdMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alerter.alertIdMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alertId = 1;</code>
   */
  java.lang.String getAlertId();
  /**
   * <code>string alertId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlertIdBytes();
}
