// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alerter.proto

package ds.alerter;

public interface AlertIdMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alerter.AlertIdMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 alertId = 1;</code>
   */
  int getAlertId();
}
