// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alerter.proto

package ds.alerter;

public final class AlerterImpl {
  private AlerterImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alerter_AlertMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alerter_AlertMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alerter_AlertDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alerter_AlertDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alerter_AlertIdMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alerter_AlertIdMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alerter_EmptyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alerter_EmptyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ralerter.proto\022\007alerter\"\217\001\n\014AlertMessag" +
      "e\022:\n\rpriorityLevel\030\001 \001(\0162#.alerter.Alert" +
      "Message.PriorityLevel\022\023\n\013description\030\002 \001" +
      "(\t\".\n\rPriorityLevel\022\n\n\006MEDIUM\020\000\022\010\n\004HIGH\020" +
      "\001\022\007\n\003LOW\020\002\"L\n\014AlertDetails\022+\n\014alertMessa" +
      "ge\030\001 \001(\0132\025.alerter.AlertMessage\022\017\n\007alert" +
      "Id\030\002 \001(\005\"!\n\016AlertIdMessage\022\017\n\007alertId\030\001 " +
      "\001(\005\"\016\n\014EmptyMessage2\313\001\n\007Alerter\022:\n\010NewAl" +
      "ert\022\025.alerter.AlertMessage\032\025.alerter.Ale" +
      "rtDetails\"\000\022>\n\nClearAlert\022\027.alerter.Aler" +
      "tIdMessage\032\025.alerter.AlertDetails\"\000\022D\n\020G" +
      "etCurrentAlerts\022\025.alerter.EmptyMessage\032\025" +
      ".alerter.AlertDetails\"\0000\001B\033\n\nds.alerterB" +
      "\013AlerterImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_alerter_AlertMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alerter_AlertMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alerter_AlertMessage_descriptor,
        new java.lang.String[] { "PriorityLevel", "Description", });
    internal_static_alerter_AlertDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alerter_AlertDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alerter_AlertDetails_descriptor,
        new java.lang.String[] { "AlertMessage", "AlertId", });
    internal_static_alerter_AlertIdMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_alerter_AlertIdMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alerter_AlertIdMessage_descriptor,
        new java.lang.String[] { "AlertId", });
    internal_static_alerter_EmptyMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_alerter_EmptyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alerter_EmptyMessage_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
