// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alerter.proto

package ds.alerter;

public final class AlerterImpl {
  private AlerterImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alerter_alertMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alerter_alertMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alerter_alertDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alerter_alertDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alerter_alertIdMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alerter_alertIdMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ralerter.proto\022\007alerter\"\217\001\n\014alertMessag" +
      "e\022:\n\rpriorityLevel\030\001 \001(\0162#.alerter.alert" +
      "Message.PriorityLevel\022\023\n\013description\030\002 \001" +
      "(\t\".\n\rPriorityLevel\022\n\n\006MEDIUM\020\000\022\010\n\004HIGH\020" +
      "\001\022\007\n\003LOW\020\002\"L\n\014alertDetails\022+\n\014alertMessa" +
      "ge\030\001 \001(\0132\025.alerter.alertMessage\022\017\n\007alert" +
      "Id\030\002 \001(\t\"!\n\016alertIdMessage\022\017\n\007alertId\030\001 " +
      "\001(\t2\205\001\n\007alerter\022:\n\010newAlert\022\025.alerter.al" +
      "ertMessage\032\025.alerter.alertDetails\"\000\022>\n\nc" +
      "learAlert\022\027.alerter.alertIdMessage\032\025.ale" +
      "rter.alertDetails\"\000B\033\n\nds.alerterB\013Alert" +
      "erImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_alerter_alertMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alerter_alertMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alerter_alertMessage_descriptor,
        new java.lang.String[] { "PriorityLevel", "Description", });
    internal_static_alerter_alertDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alerter_alertDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alerter_alertDetails_descriptor,
        new java.lang.String[] { "AlertMessage", "AlertId", });
    internal_static_alerter_alertIdMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_alerter_alertIdMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alerter_alertIdMessage_descriptor,
        new java.lang.String[] { "AlertId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
