// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alerter.proto

package ds.alerter;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alerter.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
