// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockManager.proto

package ds.stockManager;

public interface EmptyStockMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stockmanager.EmptyStockMessage)
    com.google.protobuf.MessageOrBuilder {
}
