// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockManager.proto

package ds.stockManager;

public interface RemoveStockMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stockmanager.RemoveStockMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *true if there was enough stock to remove and was removed.
   * </pre>
   *
   * <code>bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();

  /**
   * <code>.stockmanager.StockMessage stockMessage = 2;</code>
   */
  boolean hasStockMessage();
  /**
   * <code>.stockmanager.StockMessage stockMessage = 2;</code>
   */
  ds.stockManager.StockMessage getStockMessage();
  /**
   * <code>.stockmanager.StockMessage stockMessage = 2;</code>
   */
  ds.stockManager.StockMessageOrBuilder getStockMessageOrBuilder();
}
