// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockManager.proto

package ds.stockManager;

public interface StockDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stockmanager.StockDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
   */
  java.util.List<ds.stockManager.StockMessage> 
      getStockMessageList();
  /**
   * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
   */
  ds.stockManager.StockMessage getStockMessage(int index);
  /**
   * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
   */
  int getStockMessageCount();
  /**
   * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
   */
  java.util.List<? extends ds.stockManager.StockMessageOrBuilder> 
      getStockMessageOrBuilderList();
  /**
   * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
   */
  ds.stockManager.StockMessageOrBuilder getStockMessageOrBuilder(
      int index);
}
