// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockManager.proto

package ds.stockManager;

/**
 * <pre>
 *database of stock, not used as message
 * </pre>
 *
 * Protobuf type {@code stockmanager.StockDatabase}
 */
public  final class StockDatabase extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:stockmanager.StockDatabase)
    StockDatabaseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StockDatabase.newBuilder() to construct.
  private StockDatabase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StockDatabase() {
    stockMessage_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StockDatabase(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              stockMessage_ = new java.util.ArrayList<ds.stockManager.StockMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            stockMessage_.add(
                input.readMessage(ds.stockManager.StockMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        stockMessage_ = java.util.Collections.unmodifiableList(stockMessage_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.stockManager.StockManagerImpl.internal_static_stockmanager_StockDatabase_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.stockManager.StockManagerImpl.internal_static_stockmanager_StockDatabase_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.stockManager.StockDatabase.class, ds.stockManager.StockDatabase.Builder.class);
  }

  public static final int STOCKMESSAGE_FIELD_NUMBER = 1;
  private java.util.List<ds.stockManager.StockMessage> stockMessage_;
  /**
   * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
   */
  public java.util.List<ds.stockManager.StockMessage> getStockMessageList() {
    return stockMessage_;
  }
  /**
   * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
   */
  public java.util.List<? extends ds.stockManager.StockMessageOrBuilder> 
      getStockMessageOrBuilderList() {
    return stockMessage_;
  }
  /**
   * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
   */
  public int getStockMessageCount() {
    return stockMessage_.size();
  }
  /**
   * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
   */
  public ds.stockManager.StockMessage getStockMessage(int index) {
    return stockMessage_.get(index);
  }
  /**
   * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
   */
  public ds.stockManager.StockMessageOrBuilder getStockMessageOrBuilder(
      int index) {
    return stockMessage_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < stockMessage_.size(); i++) {
      output.writeMessage(1, stockMessage_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < stockMessage_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, stockMessage_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.stockManager.StockDatabase)) {
      return super.equals(obj);
    }
    ds.stockManager.StockDatabase other = (ds.stockManager.StockDatabase) obj;

    boolean result = true;
    result = result && getStockMessageList()
        .equals(other.getStockMessageList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStockMessageCount() > 0) {
      hash = (37 * hash) + STOCKMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getStockMessageList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.stockManager.StockDatabase parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.stockManager.StockDatabase parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.stockManager.StockDatabase parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.stockManager.StockDatabase parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.stockManager.StockDatabase parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.stockManager.StockDatabase parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.stockManager.StockDatabase parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.stockManager.StockDatabase parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.stockManager.StockDatabase parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.stockManager.StockDatabase parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.stockManager.StockDatabase parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.stockManager.StockDatabase parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.stockManager.StockDatabase prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *database of stock, not used as message
   * </pre>
   *
   * Protobuf type {@code stockmanager.StockDatabase}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stockmanager.StockDatabase)
      ds.stockManager.StockDatabaseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.stockManager.StockManagerImpl.internal_static_stockmanager_StockDatabase_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.stockManager.StockManagerImpl.internal_static_stockmanager_StockDatabase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.stockManager.StockDatabase.class, ds.stockManager.StockDatabase.Builder.class);
    }

    // Construct using ds.stockManager.StockDatabase.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStockMessageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (stockMessageBuilder_ == null) {
        stockMessage_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        stockMessageBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.stockManager.StockManagerImpl.internal_static_stockmanager_StockDatabase_descriptor;
    }

    @java.lang.Override
    public ds.stockManager.StockDatabase getDefaultInstanceForType() {
      return ds.stockManager.StockDatabase.getDefaultInstance();
    }

    @java.lang.Override
    public ds.stockManager.StockDatabase build() {
      ds.stockManager.StockDatabase result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.stockManager.StockDatabase buildPartial() {
      ds.stockManager.StockDatabase result = new ds.stockManager.StockDatabase(this);
      int from_bitField0_ = bitField0_;
      if (stockMessageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          stockMessage_ = java.util.Collections.unmodifiableList(stockMessage_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.stockMessage_ = stockMessage_;
      } else {
        result.stockMessage_ = stockMessageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.stockManager.StockDatabase) {
        return mergeFrom((ds.stockManager.StockDatabase)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.stockManager.StockDatabase other) {
      if (other == ds.stockManager.StockDatabase.getDefaultInstance()) return this;
      if (stockMessageBuilder_ == null) {
        if (!other.stockMessage_.isEmpty()) {
          if (stockMessage_.isEmpty()) {
            stockMessage_ = other.stockMessage_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStockMessageIsMutable();
            stockMessage_.addAll(other.stockMessage_);
          }
          onChanged();
        }
      } else {
        if (!other.stockMessage_.isEmpty()) {
          if (stockMessageBuilder_.isEmpty()) {
            stockMessageBuilder_.dispose();
            stockMessageBuilder_ = null;
            stockMessage_ = other.stockMessage_;
            bitField0_ = (bitField0_ & ~0x00000001);
            stockMessageBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStockMessageFieldBuilder() : null;
          } else {
            stockMessageBuilder_.addAllMessages(other.stockMessage_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.stockManager.StockDatabase parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.stockManager.StockDatabase) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ds.stockManager.StockMessage> stockMessage_ =
      java.util.Collections.emptyList();
    private void ensureStockMessageIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        stockMessage_ = new java.util.ArrayList<ds.stockManager.StockMessage>(stockMessage_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ds.stockManager.StockMessage, ds.stockManager.StockMessage.Builder, ds.stockManager.StockMessageOrBuilder> stockMessageBuilder_;

    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public java.util.List<ds.stockManager.StockMessage> getStockMessageList() {
      if (stockMessageBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stockMessage_);
      } else {
        return stockMessageBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public int getStockMessageCount() {
      if (stockMessageBuilder_ == null) {
        return stockMessage_.size();
      } else {
        return stockMessageBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public ds.stockManager.StockMessage getStockMessage(int index) {
      if (stockMessageBuilder_ == null) {
        return stockMessage_.get(index);
      } else {
        return stockMessageBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public Builder setStockMessage(
        int index, ds.stockManager.StockMessage value) {
      if (stockMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockMessageIsMutable();
        stockMessage_.set(index, value);
        onChanged();
      } else {
        stockMessageBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public Builder setStockMessage(
        int index, ds.stockManager.StockMessage.Builder builderForValue) {
      if (stockMessageBuilder_ == null) {
        ensureStockMessageIsMutable();
        stockMessage_.set(index, builderForValue.build());
        onChanged();
      } else {
        stockMessageBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public Builder addStockMessage(ds.stockManager.StockMessage value) {
      if (stockMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockMessageIsMutable();
        stockMessage_.add(value);
        onChanged();
      } else {
        stockMessageBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public Builder addStockMessage(
        int index, ds.stockManager.StockMessage value) {
      if (stockMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockMessageIsMutable();
        stockMessage_.add(index, value);
        onChanged();
      } else {
        stockMessageBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public Builder addStockMessage(
        ds.stockManager.StockMessage.Builder builderForValue) {
      if (stockMessageBuilder_ == null) {
        ensureStockMessageIsMutable();
        stockMessage_.add(builderForValue.build());
        onChanged();
      } else {
        stockMessageBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public Builder addStockMessage(
        int index, ds.stockManager.StockMessage.Builder builderForValue) {
      if (stockMessageBuilder_ == null) {
        ensureStockMessageIsMutable();
        stockMessage_.add(index, builderForValue.build());
        onChanged();
      } else {
        stockMessageBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public Builder addAllStockMessage(
        java.lang.Iterable<? extends ds.stockManager.StockMessage> values) {
      if (stockMessageBuilder_ == null) {
        ensureStockMessageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stockMessage_);
        onChanged();
      } else {
        stockMessageBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public Builder clearStockMessage() {
      if (stockMessageBuilder_ == null) {
        stockMessage_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        stockMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public Builder removeStockMessage(int index) {
      if (stockMessageBuilder_ == null) {
        ensureStockMessageIsMutable();
        stockMessage_.remove(index);
        onChanged();
      } else {
        stockMessageBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public ds.stockManager.StockMessage.Builder getStockMessageBuilder(
        int index) {
      return getStockMessageFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public ds.stockManager.StockMessageOrBuilder getStockMessageOrBuilder(
        int index) {
      if (stockMessageBuilder_ == null) {
        return stockMessage_.get(index);  } else {
        return stockMessageBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public java.util.List<? extends ds.stockManager.StockMessageOrBuilder> 
         getStockMessageOrBuilderList() {
      if (stockMessageBuilder_ != null) {
        return stockMessageBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stockMessage_);
      }
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public ds.stockManager.StockMessage.Builder addStockMessageBuilder() {
      return getStockMessageFieldBuilder().addBuilder(
          ds.stockManager.StockMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public ds.stockManager.StockMessage.Builder addStockMessageBuilder(
        int index) {
      return getStockMessageFieldBuilder().addBuilder(
          index, ds.stockManager.StockMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .stockmanager.StockMessage StockMessage = 1;</code>
     */
    public java.util.List<ds.stockManager.StockMessage.Builder> 
         getStockMessageBuilderList() {
      return getStockMessageFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ds.stockManager.StockMessage, ds.stockManager.StockMessage.Builder, ds.stockManager.StockMessageOrBuilder> 
        getStockMessageFieldBuilder() {
      if (stockMessageBuilder_ == null) {
        stockMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ds.stockManager.StockMessage, ds.stockManager.StockMessage.Builder, ds.stockManager.StockMessageOrBuilder>(
                stockMessage_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        stockMessage_ = null;
      }
      return stockMessageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:stockmanager.StockDatabase)
  }

  // @@protoc_insertion_point(class_scope:stockmanager.StockDatabase)
  private static final ds.stockManager.StockDatabase DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.stockManager.StockDatabase();
  }

  public static ds.stockManager.StockDatabase getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StockDatabase>
      PARSER = new com.google.protobuf.AbstractParser<StockDatabase>() {
    @java.lang.Override
    public StockDatabase parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StockDatabase(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StockDatabase> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StockDatabase> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.stockManager.StockDatabase getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

