// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockManager.proto

package ds.stockManager;

public interface StockMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stockmanager.StockMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stockType = 1;</code>
   */
  java.lang.String getStockType();
  /**
   * <code>string stockType = 1;</code>
   */
  com.google.protobuf.ByteString
      getStockTypeBytes();

  /**
   * <code>double stockVolume = 2;</code>
   */
  double getStockVolume();
}
