// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animalLocator.proto

package ds.animalLocator;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animalLocator.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
