// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animalLocator.proto

package ds.animalLocator;

/**
 * Protobuf type {@code animalLocator.HeardMemeberNMessage}
 */
public  final class HeardMemeberNMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:animalLocator.HeardMemeberNMessage)
    HeardMemeberNMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeardMemeberNMessage.newBuilder() to construct.
  private HeardMemeberNMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeardMemeberNMessage() {
    animalId_ = "";
    n_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeardMemeberNMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            animalId_ = s;
            break;
          }
          case 16: {

            n_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.animalLocator.AnimalLocatorImpl.internal_static_animalLocator_HeardMemeberNMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.animalLocator.AnimalLocatorImpl.internal_static_animalLocator_HeardMemeberNMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.animalLocator.HeardMemeberNMessage.class, ds.animalLocator.HeardMemeberNMessage.Builder.class);
  }

  public static final int ANIMALID_FIELD_NUMBER = 1;
  private volatile java.lang.Object animalId_;
  /**
   * <code>string animalId = 1;</code>
   */
  public java.lang.String getAnimalId() {
    java.lang.Object ref = animalId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      animalId_ = s;
      return s;
    }
  }
  /**
   * <code>string animalId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAnimalIdBytes() {
    java.lang.Object ref = animalId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      animalId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int N_FIELD_NUMBER = 2;
  private int n_;
  /**
   * <code>int32 N = 2;</code>
   */
  public int getN() {
    return n_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAnimalIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, animalId_);
    }
    if (n_ != 0) {
      output.writeInt32(2, n_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAnimalIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, animalId_);
    }
    if (n_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, n_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.animalLocator.HeardMemeberNMessage)) {
      return super.equals(obj);
    }
    ds.animalLocator.HeardMemeberNMessage other = (ds.animalLocator.HeardMemeberNMessage) obj;

    boolean result = true;
    result = result && getAnimalId()
        .equals(other.getAnimalId());
    result = result && (getN()
        == other.getN());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ANIMALID_FIELD_NUMBER;
    hash = (53 * hash) + getAnimalId().hashCode();
    hash = (37 * hash) + N_FIELD_NUMBER;
    hash = (53 * hash) + getN();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.animalLocator.HeardMemeberNMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.animalLocator.HeardMemeberNMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.animalLocator.HeardMemeberNMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code animalLocator.HeardMemeberNMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:animalLocator.HeardMemeberNMessage)
      ds.animalLocator.HeardMemeberNMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.animalLocator.AnimalLocatorImpl.internal_static_animalLocator_HeardMemeberNMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.animalLocator.AnimalLocatorImpl.internal_static_animalLocator_HeardMemeberNMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.animalLocator.HeardMemeberNMessage.class, ds.animalLocator.HeardMemeberNMessage.Builder.class);
    }

    // Construct using ds.animalLocator.HeardMemeberNMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      animalId_ = "";

      n_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.animalLocator.AnimalLocatorImpl.internal_static_animalLocator_HeardMemeberNMessage_descriptor;
    }

    @java.lang.Override
    public ds.animalLocator.HeardMemeberNMessage getDefaultInstanceForType() {
      return ds.animalLocator.HeardMemeberNMessage.getDefaultInstance();
    }

    @java.lang.Override
    public ds.animalLocator.HeardMemeberNMessage build() {
      ds.animalLocator.HeardMemeberNMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.animalLocator.HeardMemeberNMessage buildPartial() {
      ds.animalLocator.HeardMemeberNMessage result = new ds.animalLocator.HeardMemeberNMessage(this);
      result.animalId_ = animalId_;
      result.n_ = n_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.animalLocator.HeardMemeberNMessage) {
        return mergeFrom((ds.animalLocator.HeardMemeberNMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.animalLocator.HeardMemeberNMessage other) {
      if (other == ds.animalLocator.HeardMemeberNMessage.getDefaultInstance()) return this;
      if (!other.getAnimalId().isEmpty()) {
        animalId_ = other.animalId_;
        onChanged();
      }
      if (other.getN() != 0) {
        setN(other.getN());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.animalLocator.HeardMemeberNMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.animalLocator.HeardMemeberNMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object animalId_ = "";
    /**
     * <code>string animalId = 1;</code>
     */
    public java.lang.String getAnimalId() {
      java.lang.Object ref = animalId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        animalId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string animalId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAnimalIdBytes() {
      java.lang.Object ref = animalId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        animalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string animalId = 1;</code>
     */
    public Builder setAnimalId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      animalId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string animalId = 1;</code>
     */
    public Builder clearAnimalId() {
      
      animalId_ = getDefaultInstance().getAnimalId();
      onChanged();
      return this;
    }
    /**
     * <code>string animalId = 1;</code>
     */
    public Builder setAnimalIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      animalId_ = value;
      onChanged();
      return this;
    }

    private int n_ ;
    /**
     * <code>int32 N = 2;</code>
     */
    public int getN() {
      return n_;
    }
    /**
     * <code>int32 N = 2;</code>
     */
    public Builder setN(int value) {
      
      n_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 N = 2;</code>
     */
    public Builder clearN() {
      
      n_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:animalLocator.HeardMemeberNMessage)
  }

  // @@protoc_insertion_point(class_scope:animalLocator.HeardMemeberNMessage)
  private static final ds.animalLocator.HeardMemeberNMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.animalLocator.HeardMemeberNMessage();
  }

  public static ds.animalLocator.HeardMemeberNMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeardMemeberNMessage>
      PARSER = new com.google.protobuf.AbstractParser<HeardMemeberNMessage>() {
    @java.lang.Override
    public HeardMemeberNMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeardMemeberNMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeardMemeberNMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeardMemeberNMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.animalLocator.HeardMemeberNMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

