// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animalLocator.proto

package ds.animalLocator;

public interface HeardMemeberNMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animalLocator.HeardMemeberNMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string animalId = 1;</code>
   */
  java.lang.String getAnimalId();
  /**
   * <code>string animalId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnimalIdBytes();

  /**
   * <code>int32 N = 2;</code>
   */
  int getN();
}
