// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animalLocator.proto

package ds.animalLocator;

/**
 * Protobuf type {@code animalLocator.LocationResponse}
 */
public  final class LocationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:animalLocator.LocationResponse)
    LocationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocationResponse.newBuilder() to construct.
  private LocationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocationResponse() {
    countRecieved_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            countRecieved_ = input.readInt32();
            break;
          }
          case 18: {
            ds.animalLocator.LocationMessage.Builder subBuilder = null;
            if (lastRecieved_ != null) {
              subBuilder = lastRecieved_.toBuilder();
            }
            lastRecieved_ = input.readMessage(ds.animalLocator.LocationMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastRecieved_);
              lastRecieved_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.animalLocator.AnimalLocatorImpl.internal_static_animalLocator_LocationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.animalLocator.AnimalLocatorImpl.internal_static_animalLocator_LocationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.animalLocator.LocationResponse.class, ds.animalLocator.LocationResponse.Builder.class);
  }

  public static final int COUNTRECIEVED_FIELD_NUMBER = 1;
  private int countRecieved_;
  /**
   * <code>int32 countRecieved = 1;</code>
   */
  public int getCountRecieved() {
    return countRecieved_;
  }

  public static final int LASTRECIEVED_FIELD_NUMBER = 2;
  private ds.animalLocator.LocationMessage lastRecieved_;
  /**
   * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
   */
  public boolean hasLastRecieved() {
    return lastRecieved_ != null;
  }
  /**
   * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
   */
  public ds.animalLocator.LocationMessage getLastRecieved() {
    return lastRecieved_ == null ? ds.animalLocator.LocationMessage.getDefaultInstance() : lastRecieved_;
  }
  /**
   * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
   */
  public ds.animalLocator.LocationMessageOrBuilder getLastRecievedOrBuilder() {
    return getLastRecieved();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (countRecieved_ != 0) {
      output.writeInt32(1, countRecieved_);
    }
    if (lastRecieved_ != null) {
      output.writeMessage(2, getLastRecieved());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (countRecieved_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, countRecieved_);
    }
    if (lastRecieved_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLastRecieved());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.animalLocator.LocationResponse)) {
      return super.equals(obj);
    }
    ds.animalLocator.LocationResponse other = (ds.animalLocator.LocationResponse) obj;

    boolean result = true;
    result = result && (getCountRecieved()
        == other.getCountRecieved());
    result = result && (hasLastRecieved() == other.hasLastRecieved());
    if (hasLastRecieved()) {
      result = result && getLastRecieved()
          .equals(other.getLastRecieved());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COUNTRECIEVED_FIELD_NUMBER;
    hash = (53 * hash) + getCountRecieved();
    if (hasLastRecieved()) {
      hash = (37 * hash) + LASTRECIEVED_FIELD_NUMBER;
      hash = (53 * hash) + getLastRecieved().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.animalLocator.LocationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.animalLocator.LocationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.animalLocator.LocationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.animalLocator.LocationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.animalLocator.LocationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.animalLocator.LocationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.animalLocator.LocationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.animalLocator.LocationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.animalLocator.LocationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.animalLocator.LocationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.animalLocator.LocationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.animalLocator.LocationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.animalLocator.LocationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code animalLocator.LocationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:animalLocator.LocationResponse)
      ds.animalLocator.LocationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.animalLocator.AnimalLocatorImpl.internal_static_animalLocator_LocationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.animalLocator.AnimalLocatorImpl.internal_static_animalLocator_LocationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.animalLocator.LocationResponse.class, ds.animalLocator.LocationResponse.Builder.class);
    }

    // Construct using ds.animalLocator.LocationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      countRecieved_ = 0;

      if (lastRecievedBuilder_ == null) {
        lastRecieved_ = null;
      } else {
        lastRecieved_ = null;
        lastRecievedBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.animalLocator.AnimalLocatorImpl.internal_static_animalLocator_LocationResponse_descriptor;
    }

    @java.lang.Override
    public ds.animalLocator.LocationResponse getDefaultInstanceForType() {
      return ds.animalLocator.LocationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.animalLocator.LocationResponse build() {
      ds.animalLocator.LocationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.animalLocator.LocationResponse buildPartial() {
      ds.animalLocator.LocationResponse result = new ds.animalLocator.LocationResponse(this);
      result.countRecieved_ = countRecieved_;
      if (lastRecievedBuilder_ == null) {
        result.lastRecieved_ = lastRecieved_;
      } else {
        result.lastRecieved_ = lastRecievedBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.animalLocator.LocationResponse) {
        return mergeFrom((ds.animalLocator.LocationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.animalLocator.LocationResponse other) {
      if (other == ds.animalLocator.LocationResponse.getDefaultInstance()) return this;
      if (other.getCountRecieved() != 0) {
        setCountRecieved(other.getCountRecieved());
      }
      if (other.hasLastRecieved()) {
        mergeLastRecieved(other.getLastRecieved());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.animalLocator.LocationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.animalLocator.LocationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int countRecieved_ ;
    /**
     * <code>int32 countRecieved = 1;</code>
     */
    public int getCountRecieved() {
      return countRecieved_;
    }
    /**
     * <code>int32 countRecieved = 1;</code>
     */
    public Builder setCountRecieved(int value) {
      
      countRecieved_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 countRecieved = 1;</code>
     */
    public Builder clearCountRecieved() {
      
      countRecieved_ = 0;
      onChanged();
      return this;
    }

    private ds.animalLocator.LocationMessage lastRecieved_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ds.animalLocator.LocationMessage, ds.animalLocator.LocationMessage.Builder, ds.animalLocator.LocationMessageOrBuilder> lastRecievedBuilder_;
    /**
     * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
     */
    public boolean hasLastRecieved() {
      return lastRecievedBuilder_ != null || lastRecieved_ != null;
    }
    /**
     * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
     */
    public ds.animalLocator.LocationMessage getLastRecieved() {
      if (lastRecievedBuilder_ == null) {
        return lastRecieved_ == null ? ds.animalLocator.LocationMessage.getDefaultInstance() : lastRecieved_;
      } else {
        return lastRecievedBuilder_.getMessage();
      }
    }
    /**
     * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
     */
    public Builder setLastRecieved(ds.animalLocator.LocationMessage value) {
      if (lastRecievedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastRecieved_ = value;
        onChanged();
      } else {
        lastRecievedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
     */
    public Builder setLastRecieved(
        ds.animalLocator.LocationMessage.Builder builderForValue) {
      if (lastRecievedBuilder_ == null) {
        lastRecieved_ = builderForValue.build();
        onChanged();
      } else {
        lastRecievedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
     */
    public Builder mergeLastRecieved(ds.animalLocator.LocationMessage value) {
      if (lastRecievedBuilder_ == null) {
        if (lastRecieved_ != null) {
          lastRecieved_ =
            ds.animalLocator.LocationMessage.newBuilder(lastRecieved_).mergeFrom(value).buildPartial();
        } else {
          lastRecieved_ = value;
        }
        onChanged();
      } else {
        lastRecievedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
     */
    public Builder clearLastRecieved() {
      if (lastRecievedBuilder_ == null) {
        lastRecieved_ = null;
        onChanged();
      } else {
        lastRecieved_ = null;
        lastRecievedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
     */
    public ds.animalLocator.LocationMessage.Builder getLastRecievedBuilder() {
      
      onChanged();
      return getLastRecievedFieldBuilder().getBuilder();
    }
    /**
     * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
     */
    public ds.animalLocator.LocationMessageOrBuilder getLastRecievedOrBuilder() {
      if (lastRecievedBuilder_ != null) {
        return lastRecievedBuilder_.getMessageOrBuilder();
      } else {
        return lastRecieved_ == null ?
            ds.animalLocator.LocationMessage.getDefaultInstance() : lastRecieved_;
      }
    }
    /**
     * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ds.animalLocator.LocationMessage, ds.animalLocator.LocationMessage.Builder, ds.animalLocator.LocationMessageOrBuilder> 
        getLastRecievedFieldBuilder() {
      if (lastRecievedBuilder_ == null) {
        lastRecievedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ds.animalLocator.LocationMessage, ds.animalLocator.LocationMessage.Builder, ds.animalLocator.LocationMessageOrBuilder>(
                getLastRecieved(),
                getParentForChildren(),
                isClean());
        lastRecieved_ = null;
      }
      return lastRecievedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:animalLocator.LocationResponse)
  }

  // @@protoc_insertion_point(class_scope:animalLocator.LocationResponse)
  private static final ds.animalLocator.LocationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.animalLocator.LocationResponse();
  }

  public static ds.animalLocator.LocationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocationResponse>
      PARSER = new com.google.protobuf.AbstractParser<LocationResponse>() {
    @java.lang.Override
    public LocationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.animalLocator.LocationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

