// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animalLocator.proto

package ds.animalLocator;

public interface LocationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animalLocator.LocationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.animalLocator.Point point = 1;</code>
   */
  boolean hasPoint();
  /**
   * <code>.animalLocator.Point point = 1;</code>
   */
  ds.animalLocator.Point getPoint();
  /**
   * <code>.animalLocator.Point point = 1;</code>
   */
  ds.animalLocator.PointOrBuilder getPointOrBuilder();

  /**
   * <code>string AnimalId = 2;</code>
   */
  java.lang.String getAnimalId();
  /**
   * <code>string AnimalId = 2;</code>
   */
  com.google.protobuf.ByteString
      getAnimalIdBytes();

  /**
   * <code>.google.protobuf.Timestamp Time = 3;</code>
   */
  boolean hasTime();
  /**
   * <code>.google.protobuf.Timestamp Time = 3;</code>
   */
  com.google.protobuf.Timestamp getTime();
  /**
   * <code>.google.protobuf.Timestamp Time = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();
}
