// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animalLocator.proto

package ds.animalLocator;

public interface LocationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animalLocator.LocationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 countRecieved = 1;</code>
   */
  int getCountRecieved();

  /**
   * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
   */
  boolean hasLastRecieved();
  /**
   * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
   */
  ds.animalLocator.LocationMessage getLastRecieved();
  /**
   * <code>.animalLocator.LocationMessage LastRecieved = 2;</code>
   */
  ds.animalLocator.LocationMessageOrBuilder getLastRecievedOrBuilder();
}
