// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animalLocator.proto

package ds.animalLocator;

public interface LocationDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animalLocator.LocationDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .animalLocator.LocationMessage locationMessage = 1;</code>
   */
  java.util.List<ds.animalLocator.LocationMessage> 
      getLocationMessageList();
  /**
   * <code>repeated .animalLocator.LocationMessage locationMessage = 1;</code>
   */
  ds.animalLocator.LocationMessage getLocationMessage(int index);
  /**
   * <code>repeated .animalLocator.LocationMessage locationMessage = 1;</code>
   */
  int getLocationMessageCount();
  /**
   * <code>repeated .animalLocator.LocationMessage locationMessage = 1;</code>
   */
  java.util.List<? extends ds.animalLocator.LocationMessageOrBuilder> 
      getLocationMessageOrBuilderList();
  /**
   * <code>repeated .animalLocator.LocationMessage locationMessage = 1;</code>
   */
  ds.animalLocator.LocationMessageOrBuilder getLocationMessageOrBuilder(
      int index);
}
